name: Push that RSS to pocket

on:
  schedule:
    # Every 2 hours
    - cron: 0 */2 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: Ansimorph/rss2pocket
        with:
          feeds: https://www.smashingmagazine.com/feed/, https://alistapart.com/main/feed/, https://markus.oberlehner.net/blog/index.xml 
          pocket_consumer_key: ${{ secrets.CONSUMER_KEY }}
          pocket_access_token: ${{ secrets.ACCESS_TOKEN }}
