name: Push that RSS to pocket

on:
  schedule:
    # Every 8 hours
    - cron: 0 */8 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: Ansimorph/rss2pocket@v1
        with:
          feeds: https://www.smashingmagazine.com/feed/, https://alistapart.com/main/feed/, https://markus.oberlehner.net/blog/index.xml, https://mxb.dev/feed.xml, https://www.matuzo.at/feed.xml, https://goodnight.at/?format=feed&amp;type=rss, https://ishadeed.com/feed.xml
          pocket_consumer_key: ${{ secrets.CONSUMER_KEY }}
          pocket_access_token: ${{ secrets.ACCESS_TOKEN }}
          my_token: ${{ secrets.GITHUB_TOKEN }}
